# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 每日热点  
    url: /categories/每日热点/ # 对应爬虫脚本里写的 categories
    weight: 20    
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
    url: uses/
    weight: 30
