# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Trending 
    url: /trending/
    weight: 20    
  - name: AI
    url: /blog/ai/
    weight: 25
  - name: Topics
    url: tags/
    weight: 30
  - name: Uses
    url: uses/
    weight: 40
